export const CHECK_LOGGED_IN_STATUS = "CHECK_LOGGED_IN_STATUS";
export const USER_LOGOUT = "USER_LOGOUT";

export const FETCH_BUCKETLISTS_SUCCESS = "FETCH_BUCKETLISTS_SUCCESS";
export const DELETE_BUCKETLIST_SUCCESS = "DELETE_BUCKETLIST_SUCCESS";
